#!/bin/sh

set -eu

echo "------------------------------"
echo "rpicam command examples"
echo "If connected over SSH, export display first:"
echo "  export DISPLAY=:0.0"
echo ""

# Preview parameters means a window location and size on the screen.
PREVIEW_TOP=100
PREVIEW_LEFT=200
PREVIEW_WIDTH=1280
PREVIEW_HEIGHT=720

# lores parameters means the size of the low resolution image that is sent to the Hailo device for inference.
LORES_WIDTH=640
LORES_HEIGHT=640

SIZE_PARAMS="--lores-width ${LORES_WIDTH} --lores-height ${LORES_HEIGHT} --preview ${PREVIEW_LEFT},${PREVIEW_TOP},${PREVIEW_WIDTH},${PREVIEW_HEIGHT}"

ASSET_DIR="/usr/share/rpi-camera-assets"

POST_PROC_INF_YOLOX="${ASSET_DIR}/hailo_yolox_inference.json"
POST_PROC_INF_YOLOV8="${ASSET_DIR}/hailo_yolov8_inference.json"
POST_PROC_INF_YOLOV5="${ASSET_DIR}/hailo_yolov5_personface.json"
POST_PROC_SEG_YOLOV5="${ASSET_DIR}/hailo_yolov5_segmentation.json"
POST_PROC_POSE_YOLOV8="${ASSET_DIR}/hailo_yolov8_pose.json"

echo "Object Detection (YOLOv6):"
echo " rpicam-hello -t 0 --qt-preview --post-process-file ${POST_PROC_INF_YOLOX} ${SIZE_PARAMS}"

echo "Object Detection (YOLOv8):"
echo "  rpicam-hello -t 0 --qt-preview --post-process-file ${POST_PROC_INF_YOLOV8} ${SIZE_PARAMS}"

echo "Object Detection (YoloX):"
echo "  rpicam-hello -t 0 --qt-preview --post-process-file ${POST_PROC_INF_YOLOX} ${SIZE_PARAMS}"

echo "Person + Face (YOLOv5):"
echo "  rpicam-hello -t 0 --qt-preview --post-process-file ${POST_PROC_INF_YOLOV5} ${SIZE_PARAMS}"

echo "Segmentation:"
echo "  rpicam-hello -t 0 --qt-preview --post-process-file ${POST_PROC_SEG_YOLOV5} ${SIZE_PARAMS} --framerate 20"

echo "Pose Estimation:"
echo "  rpicam-hello -t 0 --qt-preview --post-process-file ${POST_PROC_POSE_YOLOV8} ${SIZE_PARAMS}"

echo "[hailo-ai-smoke-test] Done"
